/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        "on-secondary-container": "#3d5780",
        "inverse-on-surface": "#f0f1f2",
        "surface": "#f8f9fa",
        "surface-container": "#edeeef",
        "on-error-container": "#93000a",
        "tertiary-container": "#895200",
        "inverse-surface": "#2e3132",
        "surface-tint": "#0056d2",
        "outline": "#737785",
        "tertiary-fixed": "#ffdcbc",
        "on-tertiary-container": "#ffd1a2",
        "on-background": "#191c1d",
        "secondary": "#465f89",
        "on-secondary-fixed": "#001b3d",
        "primary": "#0040a1",
        "surface-variant": "#e1e3e4",
        "on-primary-fixed": "#001847",
        "error-container": "#ffdad6",
        "on-surface": "#191c1d",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#2d4770",
        "inverse-primary": "#b2c5ff",
        "primary-fixed-dim": "#b2c5ff",
        "secondary-fixed": "#d6e3ff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#ffb86a",
        "surface-bright": "#f8f9fa",
        "error": "#ba1a1a",
        "background": "#f8f9fa",
        "on-secondary": "#ffffff",
        "primary-container": "#0056d2",
        "on-primary-fixed-variant": "#0040a1",
        "secondary-fixed-dim": "#aec7f7",
        "secondary-container": "#b3cdfd",
        "on-error": "#ffffff",
        "tertiary": "#683d00",
        "primary-fixed": "#dae2ff",
        "outline-variant": "#c3c6d6",
        "surface-container-highest": "#e1e3e4",
        "on-surface-variant": "#424654",
        "surface-dim": "#d9dadb",
        "on-tertiary-fixed": "#2c1700",
        "surface-container-low": "#f3f4f5",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#683d00",
        "on-primary-container": "#ccd8ff",
        "surface-container-high": "#e7e8e9"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};